FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app

# copy sln and csproj files into the image
COPY *.sln .
COPY src/kata_frameworkless_web_app/*.csproj ./src/kata_frameworkless_web_app/
COPY src/kata_frameworkless_basic_web_application.tests/*.csproj ./src/kata_frameworkless_basic_web_application.tests/
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet build

#run the unit tests
FROM build AS test
WORKDIR /app/src/kata_frameworkless_basic_web_application.tests
RUN ls
RUN dotnet test