FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && apt-get update && apt-get install unzip && unzip awscliv2.zip && ./aws/install
COPY /ops/scripts/dynamo_db_local_install.sh ./
RUN sh dynamo_db_local_install.sh
WORKDIR /app

# copy sln and csproj files into the image
COPY *.sln .
COPY src/kata_frameworkless_web_app/*.csproj ./src/kata_frameworkless_web_app/
COPY src/kata.users.domain/*.csproj ./src/kata.users.domain/
COPY src/kata.users.repositories/*.csproj ./src/kata.users.repositories/
COPY src/kata.users.shared/*.csproj ./src/kata.users.shared/
COPY src/kata_frameworkless_web_app.tests/*.csproj ./src/kata_frameworkless_web_app.tests/
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet build

#run the unit tests
FROM build AS test
WORKDIR /app/src/kata_frameworkless_web_app.tests
COPY /ops/scripts/test_with_dynamodb.sh ./
COPY /dynamodb_local/tables/ ./dynamodb_local/tables/
COPY /dynamodb_local/testusers.json ./dynamodb_local/
#RUN sh test_with_dynamodb.sh
CMD [ "sh", "test_with_dynamodb.sh" ]




