steps:
  - label: "Test"
    command: 
      - .buildkite/test.sh
    plugins:
      - docker-compose#v3.4.0:
          run: app
          config:
            - docker-compose.yml
    agents:
      queue: "katherine-lab"
    