steps:
  - label: ":test_tube: Running Tests"
    command: 
      - "./ops/scripts/test.sh $(git rev-parse --short HEAD)"
    artifact_paths:
      - "/app/src/kata_frameworkless_web_app/publish"
    agents:
     queue: "katherine-lab"
 
  - wait
      
  - label: ":docker: Publish and push image to ECR"
    command:
      - "./ops/scripts/publish.sh $(git rev-parse --short HEAD)"
    branches: master
    agents:
      queue: "katherine-lab"
    plugins:
      - ecr#v2.1.1:
          login: true
           
  - wait
    
  - label: ":rocket: Deploy to Jupiter"
    command:
      - "./ops/scripts/deploy.sh $(git rev-parse --short HEAD)"
    branches: master
    agents:
      queue: "europa-preprod-fma"
      

  
  
    