steps:
 - label: ":test_tube: Running Tests"
   command: 
     - ls
     - ./ops/scripts/test.sh ${BUILDKITE_BUILD_NUMBER}
  #  artifact_paths:
  #    - "src/kata_frameworkless_web_app/**/*"
  #    - "src/kata.users.domain/**/*"
  #    - "src/kata.users.shared/**/*"
  #    - "src/kata.users.repositories/**/*"
   agents:
     queue: "katherine-lab"

  - wait
      
  - label: ":docker: Publish and push image to ECR"
    command:
      - "./ops/scripts/publish.sh ${BUILDKITE_BUILD_NUMBER}"
    #branches: master
    agents:
      queue: "katherine-lab"
    plugins:
      - ecr#v2.1.1:
          login: true
           
  - wait
    
  - label: ":rocket: Deploy to Jupiter"
    command:
      - "./ops/scripts/deploy.sh ${BUILDKITE_BUILD_NUMBER}"
    # branches: master
    agents:
      queue: "europa-preprod-fma"
      

  
  
    