steps:
  - label: "Unit Tests"
    command: 
      - ./ops/scripts/test.sh
    agents:
      queue: "katherine-lab"
      
  - wait
    
  - label: "Build and push to ECR"
    command:
      - "./ops/scripts/build_deploy_image.sh ${BUILDKITE_BUILD_NUMBER}"
    agents:
      queue: "katherine-lab"
    plugins:
      - ecr#v2.1.1:
          login: true

  
  
    