steps:
  
  - label: ":test_tube: Building image for testing"
    artifact_paths:
      - "src/nhan-frameworkless-web-app/"
    agents:
      queue: "katherine-lab"
    plugins:
      - docker-compose#v3.0.3:
          build: test
          
        
#  - wait
#    
#  - label: ":test_tube: Running Tests"
#    command: 
#      - "./ops/scripts/test.sh $(git rev-parse --short HEAD)"
#    agents:
#     queue: "katherine-lab"
 
  - wait

  - label: ":docker: Publish and push image to ECR"
    command:
      - "./ops/scripts/publish.sh $(git rev-parse --short HEAD)"
    #branches: master
    agents:
      queue: "katherine-lab"
    plugins:
      - ecr#v2.1.1:
          login: true
           
  - wait
    
  - label: ":rocket: Deploy to Jupiter"
    command:
      - "./ops/scripts/deploy.sh $(git rev-parse --short HEAD)"
    branches: master
    agents:
      queue: "europa-preprod-fma"
      

  
  
    