steps:
#  - label: "Unit Tests"
#    command: 
#      - ./ops/scripts/test.sh
#    agents:
#      queue: "katherine-lab"
#      
#  - wait
  - label: "Setting up DynamoDb Local"
    command:
      - "./dynamodb_local/dynamodb_local_startup.sh"
    agents:
      queue: "katherine-lab"
#      plugins:
#        - docker-compose#v3.5.0:
#            run: app
#            config:
#              - docker-compose-dynamodb-local.yml
  - wait
      
  - label: ":hammer: Test, Build and push to ECR"
    command:
      - "./ops/scripts/build_push_image.sh ${BUILDKITE_BUILD_NUMBER}"
#    branches: master
    agents:
      queue: "katherine-lab"
    plugins:
      - ecr#v2.1.1:
          login: true
           
  - wait
    
  - label: ":rocket: Deploy to Jupiter"
    command:
      - "./ops/scripts/deploy.sh ${BUILDKITE_BUILD_NUMBER}"
#    branches: master
    agents:
      queue: "europa-preprod-fma"
      

  
  
    