steps:
  
#  - label: ":test_tube: Building image for testing"
#    artifact_paths:
#      - "src/**/*"
#    agents:
#      queue: "katherine-lab"
#    plugins:
#      - docker-compose#v3.0.3:
#          run: app
#          
#        
#  - wait

  - label: ":test_tube: Build test image and run tests"
    command: 
      - "./ops/scripts/test.sh $(git rev-parse --short HEAD)"
    agents:
     queue: "katherine-lab"
 
  - wait
    
  - label: ":pick: Publish application"
    command: "dotnet publish src/kata_frameworkless_web_app -c Release -o publish"
    plugins:
      - docker#v3.5.0:
          image: "mcr.microsoft.com/dotnet/core/sdk"
          always-pull: true
    artifact_paths:
      - "src/kata_frameworkless_web_app/publish/*"
          
  - wait

  - label: ":docker: Build runtime image and push to ECR"
    command:
      - "./ops/scripts/publish.sh $(git rev-parse --short HEAD)"
    #branches: master
    agents:
      queue: "katherine-lab"
    plugins:
      - ecr#v2.1.1:
          login: true
           
  - wait
    
  - label: ":rocket: Deploy to Jupiter"
    command:
      - "./ops/scripts/deploy.sh $(git rev-parse --short HEAD)"
    branches: master
    agents:
      queue: "europa-preprod-fma"
      

  
  
    