steps:
#  - label: "Unit Tests"
#    command: 
#      - ./ops/scripts/test.sh
#    agents:
#      queue: "katherine-lab"
#      
#  - wait

  - label: ":hammer: Test, Build and push to ECR"
    command:
      - "./ops/scripts/build_push_image.sh"
    agents:
      queue: "katherine-lab"
    plugins:
      - ecr#v2.1.1:
          login: true
          
  - wait
    
  - label: ":rocket: Deploy to Jupiter"
    command:
      - "./ops/scripts/deploy.sh"
    #branches: master
    agents:
      queue: "europa-preprod-fma"
      

  
  
    