steps:
 - label: ":test_tube: Running Tests"
   command: 
     - ./ops/scripts/test.sh
   artifact_paths:
     - "nhan-app/**/*"
   agents:
     queue: "katherine-lab"

  # - wait
      
  # - label: ":docker: Build and push image to ECR"
  #   command:
  #     - "./ops/scripts/build_push_image.sh ${BUILDKITE_BUILD_NUMBER}"
  #   #branches: master
  #   agents:
  #     queue: "katherine-lab"
  #   plugins:
  #     - ecr#v2.1.1:
  #         login: true
           
  # - wait
    
  # - label: ":rocket: Deploy to Jupiter"
  #   command:
  #     - "./ops/scripts/deploy.sh ${BUILDKITE_BUILD_NUMBER}"
  #   # branches: master
  #   agents:
  #     queue: "europa-preprod-fma"
      

  
  
    