steps:
  - label: ":test_tube: Running Tests"
    command: 
      - "./ops/scripts/test.sh $(git rev-parse --short HEAD)"
    agents:
     queue: "katherine-lab"
 
  - wait
  
  - label: ":pick: Publishing artifact"
    command:
      - dotnet publish src/kata_Frameworkless_web_app -c Release -o src/publish
    artifact_paths:
      - src/publish
    agents:
      queue: "katherine-lab"
      
  - wait
      
  - label: ":docker: Publish and push image to ECR"
    command:
      - "./ops/scripts/publish.sh $(git rev-parse --short HEAD)"
    #branches: master
    agents:
      queue: "katherine-lab"
    plugins:
      - ecr#v2.1.1:
          login: true
           
  - wait
    
  - label: ":rocket: Deploy to Jupiter"
    command:
      - "./ops/scripts/deploy.sh $(git rev-parse --short HEAD)"
    #branches: master
    agents:
      queue: "europa-preprod-fma"
      

  
  
    