steps:
  - label: "Restore"
    command: "dotnet restore"
    agents:
      queue: "katherine-lab"
    
  - wait
    
  - label: "Build"
    command: "dotnet build"
    agents:
      queue: "katherine-lab"
    
  - wait
    
  - label: "Test"
    command: "dotnet test"
    agents:
      queue: "katherine-lab"